apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: my-cluster
  namespace: genesis
  labels:
    cni: calico  

spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.244.0.0/16

    services:
      cidrBlocks:
        - 10.96.0.0/12

    serviceDomain: cluster.local

  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: ProxmoxCluster
    name: my-proxmox-cluster

  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: my-cluster-control-plane