apiVersion: v1
kind: Secret

metadata:
  name: proxmox-credentials
  namespace: genesis

type: Opaque

stringData:
  url: "https://10.99.0.67:8006"
  token: "root@pam!capmox"
  secret: "62679c60-0b49-497f-868e-b7604e588b47"