apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxMachineTemplate
metadata:
  name: worker-template

spec:
  template:
    spec:
      sourceNode: dev-monitor
      templateID: 109
      numCores: 2
      memoryMiB: 2048

